# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

"""Helper functions for DLLM scheduling in vLLM."""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from vllm.v1.request import Request


def should_continue_refining_block(request: "Request") -> bool:
    """Check if DLLM request should continue refining current block.

    Args:
        request: The request to check

    Returns:
        True if request should continue refining, False if should advance
    """
    if not request.is_dllm:
        return False

    # Check if we've reached max iterations for this block
    if request.dllm_current_iteration >= request.dllm_denoising_steps:
        return False

    # Check if current block is complete
    return not request.dllm_is_current_block_complete()


def get_dllm_num_new_tokens(request: "Request") -> int:
    """Calculate number of new tokens to schedule for DLLM request.

    For DLLM:
    - If refining current block: 0 (no new KV cache slots)
    - If advancing to next block: block_size tokens

    Args:
        request: The DLLM request

    Returns:
        Number of new tokens to schedule
    """
    if not request.is_dllm:
        raise ValueError("Request is not a DLLM request")

    if should_continue_refining_block(request):
        # Continue refining current block, no new tokens
        return 0
    else:
        # Advance to next block
        return request.dllm_block_size


def prepare_dllm_next_block(request: "Request") -> None:
    """Prepare DLLM request for next block generation.

    This should be called when a block is complete and we're ready
    to generate the next block.

    Args:
        request: The DLLM request
    """
    if not request.is_dllm:
        return

    # Mark current block as cached
    request.dllm_advance_to_next_block()

    # Initialize new masked block
    new_block_tokens = [request.dllm_mask_token_id] * request.dllm_block_size
    request.dllm_init_new_block(new_block_tokens)


def update_dllm_from_output(
    request: "Request",
    generated_token_ids: list[int],
    dllm_mask: list[int] | None,
) -> tuple[list[int], bool]:
    """Update DLLM request from model output.

    Args:
        request: The DLLM request
        generated_token_ids: Tokens generated by the model
        dllm_mask: Updated mask state from unmasking processor

    Returns:
        Tuple of (tokens_to_append, is_stopped)
        - tokens_to_append: Only unmasked tokens that should be added to output
        - is_stopped: Whether generation should stop
    """
    if not request.is_dllm:
        return generated_token_ids, False

    from vllm.v1.sample.dllm_constants import DLLMMaskState

    # Update mask state
    if dllm_mask is not None:
        request.dllm_update_mask(dllm_mask)

    # Only append tokens that are unmasked
    tokens_to_append = []
    current_mask = request.dllm_get_mask()

    # Get the last block_size tokens from mask (current block)
    block_size = request.dllm_block_size
    if len(current_mask) >= block_size:
        block_mask = current_mask[-block_size:]

        # Check which tokens in the generated block are unmasked
        for i, (token, mask_state) in enumerate(
            zip(generated_token_ids[:block_size], block_mask)
        ):
            if mask_state == DLLMMaskState.UNMASKED:
                tokens_to_append.append(token)

    # Check if we should stop
    is_stopped = False
    if request.dllm_num_valid_tokens >= request.max_tokens:
        is_stopped = True
    elif request.dllm_is_current_block_complete():
        # Block is complete, check if we have enough tokens
        if (
            request.dllm_num_valid_tokens + request.dllm_block_size
            >= request.max_tokens
        ):
            is_stopped = True

    return tokens_to_append, is_stopped


def check_dllm_ready_for_next_block(request: "Request") -> bool:
    """Check if DLLM request is ready to advance to next block.

    Args:
        request: The DLLM request

    Returns:
        True if ready to advance, False otherwise
    """
    if not request.is_dllm:
        return False

    # Check if current block is complete
    if not request.dllm_is_current_block_complete():
        return False

    # Check if we haven't exceeded max tokens
    if request.dllm_num_valid_tokens >= request.max_tokens:
        return False

    return True


def get_dllm_schedule_info(request: "Request") -> dict:
    """Get DLLM scheduling information for logging/debugging.

    Args:
        request: The DLLM request

    Returns:
        Dictionary with DLLM scheduling info
    """
    if not request.is_dllm:
        return {}

    return {
        "is_dllm": True,
        "block_size": request.dllm_block_size,
        "denoising_steps": request.dllm_denoising_steps,
        "current_iteration": request.dllm_current_iteration,
        "num_valid_tokens": request.dllm_num_valid_tokens,
        "is_block_complete": request.dllm_is_current_block_complete(),
        "should_continue_refining": should_continue_refining_block(request),
    }
